/* Türkiye Siyasi Partileri Soyağacı — ortak veri.
   index.html ve sandik.html tarafından paylaşılır; tek kaynak burasıdır. */
window.PARTILER = (function(){
  const AILE = [
    {ad:"Cumhuriyetçi / sosyal demokrat", ham:"#C0392B"},
    {ad:"Merkez sağ", ham:"#B57B18"},
    {ad:"Milli Görüş / muhafazakâr", ham:"#25795A"},
    {ad:"Milliyetçi", ham:"#28457A"},
    {ad:"Sosyalist sol", ham:"#8E2050"},
    {ad:"Radikal sol", ham:"#7B3F9D"},
    {ad:"Liberal", ham:"#0F7A80"}
  ];

  const BILGI = {
    chp23:{k:"Mustafa Kemal Atatürk", o:"Kurtuluş Savaşı'nı yürüten Anadolu ve Rumeli Müdafaa-i Hukuk Cemiyeti'nin partiye dönüşmesiyle doğdu. 1946'ya kadar tek parti olarak ülkeyi yönetti, 1950'de iktidarı seçimle devretti. 1965'ten sonra Ecevit önderliğinde \"ortanın solu\" çizgisine kaydı ve 12 Eylül'e kadar sosyal demokrat bir kitle partisi oldu."},
    tcf:{k:"Kâzım Karabekir, Rauf Orbay, Ali Fuat Cebesoy", o:"Cumhuriyetin ilk muhalefet partisi. Kurtuluş Savaşı'nın önde gelen komutanları tarafından, tek elde toplanan yetkiye itiraz olarak kuruldu. Şeyh Sait İsyanı'nın ardından Takrir-i Sükûn Kanunu'na dayanılarak kapatıldı."},
    scf:{k:"Fethi Okyar", o:"Denetimli bir muhalefet yaratmak amacıyla, Mustafa Kemal Atatürk'ün isteğiyle kuruldu. Kısa sürede rejim karşıtı unsurların partinin tabanına yayılması üzerine, Fethi Okyar kendi kararıyla partiyi feshetti."},
    tkp20:{k:"Mustafa Suphi", o:"Bakü'de, Kızıl Ordu kulübünde 74 delegenin katılımıyla kuruldu; Türkiye'de değil yurt dışında doğdu. Suphi ve on dört yoldaşı 1921 başında Trabzon açıklarında öldürüldü. Parti bundan sonra onlarca yıl boyunca yasa dışı çalıştı, 1988'de kendini feshederek TBKP'ye katıldı."},
    thif:{k:"Şerif Manatov, Salih Hacıoğlu", o:"TKP'nin Ankara'daki yasal görünümlü kolu olarak kuruldu. Birkaç ay içinde kapatıldı, 1922 yazında kısa süre yeniden faaliyet gösterebildi. Şemadaki en kısa ömürlü parti."},
    dp46:{k:"Celâl Bayar, Adnan Menderes", o:"CHP'den ayrılan \"Dörtlü Takrir\" imzacıları tarafından kuruldu ve çok partili hayatın başlangıcı oldu. 1950 seçimini kazanarak on yıl iktidarda kaldı; kırsal kalkınma, karayolu ve tarım politikalarıyla anıldı. 27 Mayıs darbesiyle kapatıldı, Menderes ve iki bakanı idam edildi."},
    mp48:{k:"Fevzi Çakmak, Osman Bölükbaşı", o:"DP'den ayrılan muhafazakâr ve milliyetçi kanadın partisi. Din ve gelenek vurgusuyla DP'nin sağında konumlandı. 1954'te mahkeme kararıyla kapatıldı; kadrosu aynı yıl Cumhuriyetçi Millet Partisi'ni kurdu."},
    ckmp:{k:"Osman Bölükbaşı", o:"Cumhuriyetçi Millet Partisi'nin 1958'de Türkiye Köylü Partisi ile birleşmesiyle bu adı aldı. 1965'te Alparslan Türkeş ve arkadaşlarının katılmasıyla yön değiştirdi ve 1969'da adını Milliyetçi Hareket Partisi olarak değiştirdi."},
    ap:{k:"Ragıp Gümüşpala, ardından Süleyman Demirel", o:"27 Mayıs sonrası DP tabanının ana adresi oldu ve 1965'te tek başına iktidara geldi. Demirel liderliğinde merkez sağın en uzun soluklu partisi haline geldi, 1970'lerde Milliyetçi Cephe hükümetlerini kurdu. 12 Eylül'le birlikte feshedildi."},
    ytp:{k:"Ekrem Alican", o:"DP mirasını paylaşan ikinci damar olarak kuruldu ve 1961–65 koalisyonlarında yer aldı. AP'nin tabanı toparlamasıyla hızla eridi."},
    demp70:{k:"Ferruh Bozbeyli", o:"AP'nin \"kırk dörtler\" olarak anılan muhalif kanadının ayrılmasıyla kuruldu. Demirel'e karşı sağda alternatif olmayı denedi ama başaramadı ve 1980'de yeniden AP'ye katıldı."},
    mhp69:{k:"Alparslan Türkeş", o:"CKMP'nin adını ve simgesini değiştirmesiyle doğdu; üç hilal ve bozkurt sembolleri bu dönemde benimsendi. 1970'lerde Milliyetçi Cephe hükümetlerine ortak oldu. 12 Eylül'de kapatıldı ve yöneticileri uzun süre yargılandı."},
    mnp:{k:"Necmettin Erbakan", o:"Milli Görüş hareketinin ilk partisi. Ağır sanayi hamlesi ve manevi kalkınma söylemiyle merkez sağdan ayrıştı. 12 Mart muhtırasının ardından laiklik gerekçesiyle kapatıldı."},
    gp:{k:"Turhan Feyzioğlu", o:"CHP'nin \"ortanın solu\" çizgisine itiraz eden 47 milletvekilinin ayrılmasıyla kuruldu. Kemalist ama sola mesafeli bir çizgi izledi. 1971'de Millî Güven Partisi adını aldı, 1973'te Cumhuriyetçi Parti ile birleşti."},
    tip61:{k:"On iki sendikacı, ardından Mehmet Ali Aybar", o:"Sosyalist solun parlamentoya ilk kez girmesini sağladı; 1965'te Millet Meclisi'ne 14 milletvekili soktu. Sosyalizmi seçim yoluyla savunan ilk yasal parti oldu. 12 Mart muhtırasının ardından Anayasa Mahkemesi tarafından kapatıldı."},
    cp72:{k:"Kemal Satır", o:"Ecevit'in CHP genel başkanı olmasına karşı çıkan 18 milletvekili tarafından kuruldu. Hiçbir genel seçime kendi adıyla giremeden, altı ay sonra Millî Güven Partisi ile birleşti."},
    cgp:{k:"Turhan Feyzioğlu", o:"MGP ile Cumhuriyetçi Parti'nin birleşmesinden doğdu. Kendini \"ne aşırı sol ne aşırı sağ\" diye tanımladı ve 1970'lerin koalisyonlarında denge unsuru oldu; Feyzioğlu I. Milliyetçi Cephe hükümetinde başbakan yardımcılığı yaptı. 12 Eylül'le feshedildi."},
    msp:{k:"Necmettin Erbakan", o:"MNP'nin kapatılmasının ardından Milli Görüş'ün ikinci partisi olarak kuruldu. 1973'te CHP ile, ardından AP ile koalisyon kurarak dönemin kilit partisi haline geldi. Kıbrıs Barış Harekâtı bu koalisyonlar döneminde gerçekleşti."},
    tip75:{k:"Behice Boran", o:"Kapatılan TİP'in kadrosuyla yeniden kuruldu; Boran, Türkiye'de bir partinin genel başkanı olan ilk kadın oldu. 12 Eylül'le kapatıldı, yöneticileri yurt dışına çıkmak zorunda kaldı."},
    hp83:{k:"Necdet Calp", o:"12 Eylül sonrası kurulmasına izin verilen üç partiden biri. CHP geleneğinin devamı sayıldı ve 1983 seçiminde ana muhalefet oldu. 1985'te SODEP ile birleşti."},
    sodep:{k:"Erdal İnönü", o:"CHP kadrolarının kurduğu, ancak 1983 seçimine katılmasına izin verilmeyen sosyal demokrat parti. İki yıl sonra Halkçı Parti ile birleşerek SHP'yi oluşturdu."},
    shp:{k:"Erdal İnönü", o:"1980'lerin sonunda sosyal demokrat solun ana partisi oldu ve 1991'de DYP ile koalisyon kurdu. Kürt sorununda açılım arayışları partinin içinde büyük gerilim yarattı; ayrılan milletvekilleri HEP'i kurdu. 1995'te CHP'ye katılarak sona erdi."},
    dsp:{k:"Rahşan Ecevit, ardından Bülent Ecevit", o:"Ecevit'e siyaset yasağı sürerken eşi Rahşan Ecevit tarafından kuruldu. CHP geleneğinden ayrı, daha ulusalcı bir sol çizgi izledi. 1999 seçiminde birinci parti oldu ve Ecevit başbakanlığında koalisyon kurdu."},
    anap:{k:"Turgut Özal", o:"12 Eylül sonrası ilk seçimi kazanarak tek başına iktidara geldi. Piyasa ekonomisine geçiş, dışa açılma ve özelleştirme politikalarıyla ekonomiyi köklü biçimde dönüştürdü. Merkez sağ, milliyetçi ve muhafazakâr \"dört eğilimi\" birleştirme iddiasıyla kuruldu."},
    dyp:{k:"Süleyman Demirel, ardından Tansu Çiller", o:"AP'nin doğrudan devamı olarak kuruldu ve kır at simgesini sürdürdü. 1991'de iktidara geldi; Çiller, Türkiye'nin ilk kadın başbakanı oldu. 2007'de Demokrat Parti adını alarak tarihe karıştı."},
    rp:{k:"Necmettin Erbakan", o:"Milli Görüş'ün üçüncü partisi. 1994 yerel seçimlerinde İstanbul ve Ankara'yı kazandı, 1995'te birinci parti oldu ve Erbakan başbakanlığında Refahyol hükümetini kurdu. 28 Şubat süreci sonrası Anayasa Mahkemesi tarafından kapatıldı."},
    mcp:{k:"Alparslan Türkeş", o:"MHP kapatıldıktan sonra aynı geleneğin devamı olarak kuruldu. Türkeş'in siyasi yasağı kalkınca partinin başına geçti ve 1993'te MHP adı geri alındı."},
    hep:{k:"Fehmi Işıklar", o:"SHP'den ihraç edilen ve istifa eden milletvekilleri tarafından kuruldu. Kürt kimliği taleplerini meclis siyasetine taşıyan ilk parti oldu. 1993'te Anayasa Mahkemesi tarafından kapatıldı; bu, uzun bir kapatma zincirinin ilk halkası oldu."},
    tbkp:{k:"Haydar Kutlu, Nihat Sargın", o:"TKP ile TİP'in yurt dışında birleşmesiyle kuruldu; kurucuları Türkiye'ye döndüklerinde tutuklandı. Bir yıl bile dayanamadan Anayasa Mahkemesi tarafından kapatıldı. Bu karar sonradan Avrupa İnsan Hakları Mahkemesi'nde Türkiye aleyhine sonuçlandı."},
    chp92:{k:"Deniz Baykal", o:"Kapatılan partilerin yeniden açılmasına izin veren 3821 sayılı yasayla, on bir yıl aradan sonra aynı adla açıldı. 1995'te SHP'yi bünyesine kattı ve sosyal demokrat solun ana partisi oldu. 2026'da 91 milletvekilinin ayrılışıyla meclisteki konumunu kaybetti."},
    dp92:{k:"Aydın Menderes ve eski Demokrat Partililer", o:"CHP ile aynı yasa sayesinde yeniden açıldı, 1946'nın DP'sinin halefi olma iddiasını taşıdı. Sık sık genel başkan değiştirdi, kayda değer bir seçim başarısı elde edemedi. 2005'te kendini feshederek isim hakkıyla ANAP'a katıldı."},
    dtp97:{k:"Hüsamettin Cindoruk", o:"Refahyol hükümetine tepki gösteren \"Yeni Oluşumcular\" DYP'den ayrılarak kurdu. 55. hükümetin ortağı oldu. 2005'te adını Hürriyet ve Değişim Partisi olarak değiştirdi."},
    ldp:{k:"Besim Tibuk", o:"Tibuk, Demokrat Parti genel başkanlığı yarışını kaybedince ayrılıp kurdu; ilk adı Liberal Parti'ydi. Klasik liberal, devletin küçültülmesini savunan bir program izledi. Simgesi yunustur ve parti hiçbir zaman meclise girememiştir."},
    ydh:{k:"Cem Boyner", o:"İş dünyası ve aydın çevrelerinin birlikte kurduğu, medyada büyük ilgi gören liberal hareket. Kurucu kadrosunun önemli bölümü TİP, TKP ve SHP gibi sol geleneklerden geliyordu. 1995 seçiminde binde beşin altında oy alınca 1997'de kendini feshetti."},
    mhp93:{k:"Alparslan Türkeş, ardından Devlet Bahçeli", o:"MÇP'nin eski adını geri almasıyla doğdu. 1999'da ikinci parti olarak koalisyon ortağı oldu; 2018'den sonra Cumhur İttifakı'nın kurucu unsuru haline geldi."},
    bbp:{k:"Muhsin Yazıcıoğlu", o:"MHP içindeki daha İslami vurgulu kanadın ayrılmasıyla kuruldu. Milliyetçilikle muhafazakârlığı birleştiren bir çizgi izledi. Yazıcıoğlu'nun 2009'da bir helikopter kazasında ölümü partide derin bir kırılma yarattı."},
    fp:{k:"Recai Kutan", o:"Refah kapatılınca kurulan Milli Görüş'ün dördüncü partisi. İçinde \"gelenekçi\" ve \"yenilikçi\" kanatların çekişmesi büyüdü. 2001'de kapatılınca bu iki kanat Saadet ve AK Parti olarak ayrıldı."},
    dep:{k:"Yaşar Kaya", o:"HEP kapatılınca kurulan ikinci halka. Milletvekillerinin dokunulmazlıklarının kaldırılıp meclis içinde gözaltına alınması Türkiye siyasetinde derin iz bıraktı. Bir yıl içinde kapatıldı."},
    hadep:{k:"Murat Bozlak", o:"DEP'in kapatılmasının ardından kuruldu ve seçim barajı yüzünden meclise giremese de yerel yönetimlerde güçlendi. 2003'te kapatıldı."},
    dehap:{k:"Mehmet Abbasoğlu", o:"HADEP hakkındaki kapatma davası sürerken yedek parti olarak kuruldu ve 2002 seçimine girdi. 2005'te DTP çatısı altında birleşme kararıyla sona erdi."},
    odp:{k:"Ufuk Uras", o:"Farklı sosyalist grupların bir araya gelmesiyle kuruldu; sol içinde çoğulculuk arayışının simgesi sayıldı. Küçük ölçekli kalsa da çevre, emek ve özgürlük gündemlerinde etkili oldu."},
    emep:{k:"Levent Tüzel", o:"Sınıf eksenli, sendikal mücadeleye dayanan bir sosyalist parti olarak kuruldu. Genellikle seçimlere ittifaklar üzerinden katıldı."},
    ip92:{k:"Doğu Perinçek", o:"Sosyalist Parti'nin kapatılmasının ardından aynı kadroyla kuruldu. Zamanla ulusalcı ve Avrasyacı bir çizgiye kaydı. 2015'te Vatan Partisi adını aldı."},
    akp:{k:"Recep Tayyip Erdoğan", o:"Fazilet Partisi'nin \"yenilikçi\" kanadı tarafından kuruldu ve kurulduktan bir yıl sonra tek başına iktidara geldi. AB üyelik süreci, ekonomik büyüme ve 2017 referandumuyla başkanlık sistemine geçiş bu dönemin dönüm noktaları oldu. Türkiye tarihinin en uzun süre kesintisiz iktidarda kalan partisidir."},
    sp:{k:"Recai Kutan", o:"Fazilet'in \"gelenekçi\" kanadının partisi; Erbakan çizgisini sürdürdü. Seçim başarısı sınırlı kaldı ama Milli Görüş'ün asıl mirasçısı olma iddiasını korudu. 2025'te Yeni Yol çatısına katıldı."},
    has:{k:"Numan Kurtulmuş", o:"Saadet Partisi genel başkanlığından ayrılan Kurtulmuş ve kadrosu tarafından kuruldu. İki yıl sonra AK Parti ile birleşerek feshedildi; Kurtulmuş burada üst düzey görevlere geldi."},
    ytp02:{k:"İsmail Cem, Hüsamettin Özkan, Kemal Derviş", o:"Ecevit'in hastalığı sırasında DSP'den istifa eden 64 vekilin 63'ünün katılımıyla kuruldu. Beklenen ilgiyi göremedi, 2002 seçiminde yüzde 1'in biraz üzerinde kaldı. 2004'te CHP'ye katıldı."},
    anadolu:{k:"Emine Ülker Tarhan", o:"CHP'den ayrılan Tarhan tarafından kuruldu. 2015 seçiminde varlık gösteremeyince aynı yıl faaliyetlerini sonlandırdı."},
    dp07:{k:"Mehmet Ağar", o:"DYP'nin adını değiştirmesiyle doğdu; 2009'da ANAP'ın katılmasıyla merkez sağın dağılmış mirasını tek çatı altında toplamayı denedi. Eski gücüne dönemedi ama meclise bağımsız adaylar ve ittifaklar üzerinden temsilci gönderdi."},
    dtp:{k:"Ahmet Türk, Aysel Tuğluk", o:"DEHAP'ın devamı olarak kuruldu ve 2007'de bağımsız adaylar yoluyla meclise grup sokmayı başardı. 2009'da Anayasa Mahkemesi tarafından kapatıldı."},
    bdp:{k:"Selahattin Demirtaş", o:"DTP hakkındaki kapatma davası sürerken hazırlık olarak kuruldu. 2014'te vekillerini HDP'ye devredip Demokratik Bölgeler Partisi adıyla yerel siyasete odaklandı."},
    hdp:{k:"Selahattin Demirtaş, Figen Yüksekdağ", o:"Kürt hareketi ile Türkiye solunu ve çevre, kadın, LGBT gibi hareketleri ortak çatıda buluşturma iddiasıyla kuruldu. Haziran 2015'te yüzde 13 alarak barajı aşan ilk parti oldu. Eş genel başkanları 2016'da tutuklandı."},
    yesilsol:{k:"Yeşiller ve Sol Gelecek Partisi kadroları", o:"Yeşil siyaset ile solu birleştirmek üzere kuruldu. HDP hakkındaki kapatma davası nedeniyle 2023 seçimlerinde HDP'nin listesi olarak kullanıldı, ardından adını değiştirdi."},
    vatan:{k:"Doğu Perinçek", o:"İşçi Partisi'nin ad değişikliğiyle doğdu. Ulusalcı, Avrasyacı ve devletçi bir çizgi izliyor; seçim desteği düşük olmakla birlikte gündem belirlemede etkili."},
    memleket:{k:"Muharrem İnce", o:"CHP'nin 2018 cumhurbaşkanı adayı olan İnce'nin partiden ayrılarak kurduğu parti. 2023 seçiminde İnce adaylıktan çekildi. 2025'te İnce CHP'ye döndü ve parti kurultay kararıyla kapandı."},
    tdp:{k:"Mustafa Sarıgül", o:"Uzun yıllar Şişli belediye başkanlığı yapan Sarıgül tarafından kuruldu. 2023'te CHP ile birleşerek sona erdi."},
    yeniparti:{k:"Özgür Özel", o:"Özel'in CHP genel başkanlığının yargı kararıyla düşmesinin ardından, 91 milletvekiliyle kuruldu ve mecliste ana muhalefet konumuna geçti. Kuruluş tarihi Lozan Antlaşması'nın yıl dönümüne denk getirildi. Türkiye tarihinde bir partinin bu ölçekte bölünmesinin ilk örneği."},
    yrp:{k:"Fatih Erbakan", o:"Necmettin Erbakan'ın oğlu tarafından, Saadet Partisi'nden ayrılarak kuruldu. 2023'te meclise girdi ve 2024 yerel seçimlerinde beklenenin üzerinde oy alarak dikkat çekti."},
    gelecek:{k:"Ahmet Davutoğlu", o:"AK Parti'nin eski başbakanı ve genel başkanı tarafından kuruldu. Kendi başına seçime girmek yerine ittifaklar üzerinden meclise vekil soktu. Temmuz 2026'da Davutoğlu tarafından feshedildi."},
    deva:{k:"Ali Babacan", o:"AK Parti'nin ekonomiden sorumlu eski bakanı tarafından kuruldu. Hukuk devleti ve ekonomi vurgusuyla merkeze oynadı, meclise ittifak yoluyla girdi."},
    yeniyol:{k:"Saadet, Gelecek ve DEVA'nın ortak girişimi", o:"Meclis grubu kurmak için tek partiden 20 vekil şartı arayan İçtüzük nedeniyle, üç parti ortak bir tüzel kişilik kurdu. Partiler örgütlerini, programlarını ve genel başkanlarını korudu; yalnızca meclis çalışmalarında birlikte hareket ediyorlar. Gelecek Partisi'nin feshiyle grubun sürekliliği tartışmalı hale geldi."},
    iyi:{k:"Meral Akşener", o:"MHP içindeki muhalif kanadın ayrılmasıyla kuruldu; Akşener, Türkiye'de bir partinin kadın genel başkanı olarak dikkat çekti. Milliyetçi ama merkeze açık bir çizgi izledi ve 2018'den itibaren muhalefet ittifaklarında yer aldı."},
    zafer:{k:"Ümit Özdağ", o:"İYİ Parti'den ayrılan Özdağ tarafından kuruldu. Göç ve sığınmacı politikalarını merkezine alan bir söylemle tanındı."},
    anahtar:{k:"Yavuz Ağıralioğlu", o:"İYİ Parti'den ayrılan Ağıralioğlu tarafından kuruldu. Resmî kısaltması A Parti; amblemindeki anahtarın MSP'nin simgesini andırması dikkat çekmişti. Henüz mecliste temsil edilmiyor."},
    dem:{k:"Tülay Hatimoğulları, Tuncer Bakırhan", o:"Yeşil Sol Parti'nin ad değişikliğiyle doğdu ve HDP kadrolarının siyasi adresi oldu. 2024 yerel seçimlerinde çok sayıda belediye kazandı."},
    cmp:{k:"Osman Bölükbaşı ve Millet Partisi kadrosu", o:"Mahkeme kararıyla kapatılan Millet Partisi'nin kadrosu tarafından 1954'te kuruldu ve aynı yıl meclise girdi. 1958'de Türkiye Köylü Partisi ile birleşerek adını Cumhuriyetçi Köylü Millet Partisi olarak değiştirdi."},
    hurriyet:{k:"Fevzi Lütfi Karaosmanoğlu ve DP'den ayrılan milletvekilleri", o:"Basın suçlarında ispat hakkını kaldıran düzenlemeye itiraz edip Demokrat Parti'den ayrılan ya da ihraç edilen milletvekillerince kuruldu. 1957 seçiminde dört milletvekili çıkardı. 1958'de kendini feshederek Cumhuriyet Halk Partisi'ne katıldı."},
    mp62:{k:"Osman Bölükbaşı", o:"Bölükbaşı'nın, partisinin İnönü koalisyonuna katılmasına karşı çıkarak CKMP'den ayrılmasıyla kuruldu; 1948 Millet Partisi'nin hukuken değil siyaseten devamıydı. 1965'te 31 milletvekili çıkardı ve 12 Eylül'ün ardından bütün partilerle birlikte kapatıldı."},
    tbp:{k:"Hasan Tahsin Berkman", o:"Alevi kökenli bir grup siyasetçi tarafından Birlik Partisi adıyla kuruldu; Atatürkçülük ve laiklik vurgusuyla başladı, zamanla sola kaydı. 1969'da sekiz milletvekiliyle meclise girdi, 1971'de adını Türkiye Birlik Partisi olarak değiştirdi. 12 Eylül'ün ardından kapatıldı."},
    mdp:{k:"Turgut Sunalp", o:"12 Eylül sonrasında askerî yönetimin desteğiyle kurulan ilk parti oldu ve 1983 seçiminde 71 milletvekiliyle üçüncü parti oldu. 4 Mayıs 1986'daki olağanüstü kongresinde kendini feshetti."},
    hudapar:{k:"Mehmet Hüseyin Yılmaz, ardından Zekeriya Yapıcıoğlu", o:"Kapatılan Mustazaf-Der derneğinin eski genel başkanı Mehmet Hüseyin Yılmaz tarafından kuruldu; akademik çalışmalarda İslami referanslı, muhafazakâr bir Kürt partisi olarak tanımlanır. 2023 seçiminde adaylarını AK Parti listelerinden gösterdi."},
    tip17:{k:"Erkan Baş", o:"1961'de kurulan TİP'in adını yeniden kullanan sosyalist parti; ikisi arasında hukuki süreklilik yoktur. 2018 ve 2023'te ittifaklar yoluyla meclise girdi ve sosyalist solun uzun aradan sonra parlamentodaki sesi oldu."},
    // --- ağaca sonradan eklenen, seçim verisinde geçen partiler ---
    tukp:{k:"Melike Bayburt, ardından Mübeccel Göktuna", o:"17 Kasım 1972'de 16 kişi tarafından kuruldu; Türkiye'nin ilk yasal kadın partisidir. Meclisteki erkek egemenliğini azaltmayı ve kadın haklarını hayata geçirmeyi amaçladı. 12 Eylül'den sonra bütün partilerle birlikte kapatıldı."},
    tsip74:{k:"Ahmet Kaçmaz, Yalçın Yusufoğlu, Oya Baydar ve arkadaşları; genel başkan Turgut Koçak", o:"12 Mart muhtırasından sonra kurulan ilk sosyalist parti oldu (16 Haziran 1974). 12 Eylül'den sonra kapatıldı; aynı adla 1993'te yeniden kuruldu."},
    sdp75:{k:"Mehmet Ali Aybar", o:"1971'de TİP'ten ayrılan Aybar ve arkadaşlarınca 30 Mayıs 1975'te Sosyalist Parti adıyla kuruldu; 1977 kurultayında Sosyalist Devrim Partisi adını aldı. Demokratik sosyalizmi savundu; 12 Eylül'den sonra kapatıldı."},
    idp:{k:"Aykut Edibali", o:"Yeniden Millî Mücadele dergisi çevresinden 48 kişinin katılımıyla 22 Mart 1984'te kuruldu. 1992'de olağanüstü kongresinde adını Millet Partisi olarak değiştirdi."},
    mp92:{k:"Aykut Edibali", o:"Islahatçı Demokrasi Partisi'nin 23 Kasım 1992'deki olağanüstü kongresinde aldığı ad; 1948 ve 1962'deki Millet Partilerinden ayrı bir partidir. Yargıtay Cumhuriyet Başsavcılığı kayıtlarında kuruluş tarihi IDP'nin kuruluş tarihidir (22 Mart 1984)."},
    sbp91:{k:"Sadun Aren", o:"TBKP, TSİP ve Sosyalist Parti'den kopan bir grup ile bağımsız sosyalist aydınlar tarafından 15 Ocak 1991'de kuruldu. Girdiği tek seçim 1994 yerel seçimi oldu; Anayasa Mahkemesi 1995'te kapattı."},
    ydp:{k:"Hasan Celal Güzel", o:"ANAP'tan ayrılan Hasan Celal Güzel tarafından 23 Kasım 1992'de kuruldu. 2002'de Cem Uzan ve arkadaşlarının katılmasıyla adını Genç Parti olarak değiştirdi."},
    sip93:{o:"1978'de TİP'teki ayrışmadan doğan Sosyalist İktidar grubunun, Anayasa Mahkemesince kapatılan Sosyalist Türkiye Partisi'nin ardından 16 Ağustos 1993'te kurduğu parti. 2001'de adını Türkiye Komünist Partisi olarak değiştirdi."},
    baris96:{k:"Ali Haydar Veziroğlu", o:"1995'te kurulan Demokratik Barış Hareketi'nin 10 Aralık 1996'da partileşmesiyle doğdu. 1999 yerel seçiminde altı belediye başkanlığı kazandı; aynı yıl son kongresinde kendini feshetti."},
    dbp96:{k:"Refik Karakoç", o:"Demokrasi ve Değişim Partisi hakkında kapatma davası açılınca parti yöneticilerince 11 Mart 1996'da kuruldu. 2002'de Hak ve Özgürlükler Partisi ile birleşti."},
    depar:{k:"Gökhan Çapoğlu", o:"DSP'den siyasete atılıp partiden ayrılan akademisyen Gökhan Çapoğlu tarafından 24 Şubat 1998'de kuruldu. 1999 seçiminde %0,12 oy aldı; 2002'de olağanüstü kongresinde kendini kapattı."},
    genc:{k:"Cem Uzan", o:"Cem Uzan ve arkadaşlarının katıldığı Yeniden Doğuş Partisi'nin 23 Ağustos 2002'de adını değiştirmesiyle doğdu. 2002 genel seçiminde %7,25 oy aldı ama yüzde 10 barajını aşamadı."},
    shp02:{k:"Murat Karayalçın", o:"24 Mayıs 2002'de kuruldu; 1985–1995 arasındaki Sosyaldemokrat Halkçı Parti'den ayrı bir partidir. 2004 yerel seçiminde DEHAP ve soldaki küçük partilerle ittifak yaptı. 2010'da Eşitlik ve Demokrasi Partisi ile birleşti."},
    btp:{k:"Ata Selçuk; 2002'den itibaren Haydar Baş", o:"25 Eylül 2001'de kuruldu; 2002'de genel başkanlığına Haydar Baş seçildi. \"Millî Ekonomi Modeli\" adlı devletçi bir ekonomi programını savundu."},
    tkp01:{o:"Sosyalist İktidar Partisi'nin 2001'de adını değiştirmesiyle doğdu; Yargıtay Cumhuriyet Başsavcılığı kayıtlarında kuruluş tarihi SİP'in kuruluş tarihidir (16 Ağustos 1993). 1920'de kurulan TKP'den ayrı bir tüzel kişiliktir."},
    hakpar:{k:"Abdülmelik Fırat", o:"11 Şubat 2002'de kuruldu. Kürt kimliğiyle öne çıkar ve Türkiye'nin federal bir yapıya kavuşmasını savunur; bu yönüyle HEP'ten HDP'ye uzanan çizgideki partilerden ayrılır."},
    edp:{o:"ÖDP'den ayrılan Özgürlükçü Sol Hareket, SHP ve Alevi Bektaşi Federasyonu yöneticilerinin görüşmeleriyle Mart 2010'da kuruldu. 25 Kasım 2012'de Yeşiller Partisi ile birleşerek Yeşiller ve Sol Gelecek Partisi'ni oluşturdu."},
    solparti:{o:"Özgürlük ve Dayanışma Partisi'nin 22 Aralık 2019'daki 8. Olağanüstü Kongresi'nde adını değiştirmesiyle doğdu. Tüzel kişiliği, 1994'te kurulan Birleşik Sosyalist Parti'ye uzanır."},
    tkp52:{k:"Remzi Oğuz Arık", o:"19 Mayıs 1952'de kuruldu; Türk milliyetçiliği ve tarımcılığı savundu. 1957 seçiminden sonra Cumhuriyetçi Millet Partisi ile birleşti; birleşik parti 1958'de Cumhuriyetçi Köylü Millet Partisi adını aldı."},
    vp54:{k:"Hikmet Kıvılcımlı", o:"22 Ekim 1954'te kuruldu. 30 Aralık 1957'de İstanbul Sulh Ceza Hakimliği kararıyla \"komünist metotla çalıştığı\" gerekçesiyle kapatıldı."},
    turkparti:{k:"Ahmet Eyüp Özgüç", o:"2 Mart 2010'da kurulan Türkiye Hareketi'nin tüzük değişikliğiyle aldığı ad. Programında insan haklarına ve kişisel özgürlüklere öncelik verdiğini belirtti; 2015 seçimlerine katıldı ve aynı yıl kongre kararıyla feshedildi."},
    hkp:{k:"Nurullah Efe", o:"15 Haziran 2005'te kuruldu. 1920'de kurulan TKP'nin ve Kıvılcımlı'nın 1954'te kurduğu Vatan Partisi'nin siyasi mirasçısı olduğunu ileri süren komünist bir partidir."}
  };

  const DONEMLER = [
    {yil:"1923 – 1945", ad:"Tek parti dönemi", kesinti:null},
    {yil:"1946 – 1960", ad:"Çok partili hayata geçiş",
     kesinti:{tarih:"1960-05-27", metin:"27 Mayıs 1960 — DP kapatıldı, liderleri idam edildi",
              yonetim:{bas:"1960-05-27", bit:"1961-10-14"}}},
    {yil:"1961 – 1971", ad:"1961 Anayasası ve yeni kurulan partiler",
     kesinti:{tarih:"1971-03-12", metin:"12 Mart 1971 — TİP ve MNP kapatıldı"}},
    {yil:"1972 – 1980", ad:"Koalisyonlar ve Milliyetçi Cephe hükümetleri",
     kesinti:{tarih:"1980-09-12", metin:"12 Eylül 1980 — parti faaliyetleri yasaklandı; 16 Ekim 1981'de 2533 sayılı kanunla hepsi feshedildi",
              yonetim:{bas:"1980-09-12", bit:"1983-11-05"}}},
    {yil:"1983 – 1990", ad:"Yeniden kuruluş", kesinti:null},
    {yil:"1991 – 2000", ad:"Koalisyonlar ve kapatma davaları",
     kesinti:{tarih:"1997-02-28", metin:"28 Şubat 1997 — MGK kararları; Refah Partisi 16 Ocak 1998'de kapatıldı"}},
    {yil:"2001 – 2015", ad:"AK Parti dönemi", kesinti:null},
    {yil:"2016 – 2026", ad:"Yeni bölünmeler ve ittifaklar", kesinti:null}
  ];

  const N = [
    // --- dönem 0 ---
    {id:"chp23", kisa:"CHP", ad:"Cumhuriyet Halk Partisi", yil:"1923 – 1981", durum:"kapatildi", aile:0, donem:0,
     sembol:"Altı Ok", not:"Cumhuriyeti kuran parti; 12 Eylül'le kapatıldı"},
    {id:"tcf", kisa:"TCF", ad:"Terakkiperver Cumhuriyet Fırkası", yil:"1924 – 1925", durum:"kapatildi", aile:0, donem:0,
     not:"İlk muhalefet partisi"},
    {id:"scf", kisa:"SCF", ad:"Serbest Cumhuriyet Fırkası", yil:"1930", durum:"kapandi", aile:0, donem:0,
     not:"Aynı yıl kendini feshetti"},
    {id:"tkp20", kisa:"TKP", ad:"Türkiye Komünist Partisi", yil:"1920 – 1988", durum:"kapatildi", aile:4, donem:0,
     not:"Bakü'de, Türkiye dışında kuruldu; yurt içinde hep yasa dışı kaldı"},
    {id:"thif", kisa:"THİF", ad:"Türkiye Halk İştirakiyun Fırkası", yil:"1920 – 1921", durum:"kapatildi", aile:4, donem:0,
     not:"TKP'nin Ankara'daki yasal kolu; birkaç ay sonra kapatıldı"},

    // --- dönem 1 ---
    {id:"dp46", kisa:"DP", ad:"Demokrat Parti", yil:"1946 – 1960", durum:"kapatildi", aile:1, donem:1,
     not:"1950–60 arası iktidar; darbeyle kapatıldı"},
    {id:"mp48", kisa:"MP", ad:"Millet Partisi", yil:"1948 – 1954", durum:"kapatildi", aile:3, donem:1},
    {id:"tkp52", kisa:"TKP", ad:"Türkiye Köylü Partisi", yil:"1952 – 1958", durum:"katildi", aile:3, donem:1,
     not:"Remzi Oğuz Arık; 1958'de CMP ile birleşip CKMP oldu"},
    {id:"cmp", kisa:"CMP", ad:"Cumhuriyetçi Millet Partisi", yil:"1954 – 1958", durum:"katildi", aile:3, donem:1,
     not:"Kapatılan Millet Partisi'nin kadrosuyla kuruldu; 1958'de adı CKMP oldu"},
    {id:"hurriyet", kisa:"HP", ad:"Hürriyet Partisi", yil:"1955 – 1958", durum:"katildi", aile:6, donem:1,
     not:"DP'den ayrılan milletvekillerince kuruldu; CHP'ye katıldı"},
    {id:"ckmp", kisa:"CKMP", ad:"Cumhuriyetçi Köylü Millet Partisi", yil:"1958 – 1969", durum:"katildi", aile:3, donem:1,
     not:"1965'te Türkeş partiye katıldı"},

    // --- dönem 2 ---
    {id:"ap", kisa:"AP", ad:"Adalet Partisi", yil:"1961 – 1981", durum:"kapatildi", aile:1, donem:2,
     sembol:"Kır at", not:"DP'nin ana halefi, Demirel liderliğinde"},
    {id:"ytp", kisa:"YTP", ad:"Yeni Türkiye Partisi", yil:"1961 – 1973", durum:"kapatildi", aile:1, donem:2,
     not:"DP mirasını paylaşan ikinci damar"},
    {id:"demp70", kisa:"DP", ad:"Demokratik Parti", yil:"1970 – 1980", durum:"katildi", aile:1, donem:2,
     not:"AP'den ayrıldı, 1980'de AP'ye döndü"},
    {id:"mhp69", kisa:"MHP", ad:"Milliyetçi Hareket Partisi", yil:"1969 – 1981", durum:"kapatildi", aile:3, donem:2,
     sembol:"Üç hilal", not:"CKMP'nin ad değişikliğiyle kuruldu"},
    {id:"mp62", kisa:"MP", ad:"Millet Partisi", yil:"1962 – 1981", durum:"kapatildi", aile:3, donem:2,
     not:"Bölükbaşı'nın CKMP'den ayrılarak yeniden kurduğu parti"},
    {id:"tbp", kisa:"TBP", ad:"Türkiye Birlik Partisi", yil:"1966 – 1981", durum:"kapatildi", aile:0, donem:2,
     not:"1971'e kadar adı Birlik Partisi'ydi"},
    {id:"mnp", kisa:"MNP", ad:"Milli Nizam Partisi", yil:"1970 – 1971", durum:"kapatildi", aile:2, donem:2,
     not:"Milli Görüş'ün ilk partisi"},
    {id:"gp", kisa:"GP", ad:"Güven Partisi / Millî Güven Partisi", yil:"1967 – 1973", durum:"katildi", aile:0, donem:2,
     not:"Feyzioğlu ve 47 vekil, \"ortanın solu\"na itiraz ederek ayrıldı"},
    {id:"tip61", kisa:"TİP", ad:"Türkiye İşçi Partisi", yil:"1961 – 1971", durum:"kapatildi", aile:4, donem:2,
     not:"Sosyalist solun meclise ilk girişi"},

    // --- dönem 3 ---
    {id:"cp72", kisa:"CP", ad:"Cumhuriyetçi Parti", yil:"1972 – 1973", durum:"katildi", aile:0, donem:3,
     not:"Ecevit'in genel başkanlığına karşı çıkan Satır ve 18 vekil"},
    {id:"cgp", kisa:"CGP", ad:"Cumhuriyetçi Güven Partisi", yil:"1973 – 1981", durum:"kapatildi", aile:0, donem:3,
     not:"MGP ile CP'nin birleşmesi; MC hükümetlerinin ortağı"},
    {id:"msp", kisa:"MSP", ad:"Milli Selamet Partisi", yil:"1972 – 1981", durum:"kapatildi", aile:2, donem:3,
     sembol:"Anahtar", not:"1970'ler koalisyonlarının değişmez ortağı"},
    {id:"tip75", kisa:"TİP", ad:"Türkiye İşçi Partisi", yil:"1975 – 1980", durum:"kapatildi", aile:4, donem:3,
     not:"Behice Boran liderliğinde yeniden kuruldu"},

    // --- dönem 4 ---
    {id:"hp83", kisa:"HP", ad:"Halkçı Parti", yil:"1983 – 1985", durum:"katildi", aile:0, donem:4},
    {id:"sodep", kisa:"SODEP", ad:"Sosyal Demokrasi Partisi", yil:"1983 – 1985", durum:"katildi", aile:0, donem:4},
    {id:"shp", kisa:"SHP", ad:"Sosyaldemokrat Halkçı Parti", yil:"1985 – 1995", durum:"katildi", aile:0, donem:4,
     not:"1995'te CHP'ye katıldı"},
    {id:"dsp", kisa:"DSP", ad:"Demokratik Sol Parti", yil:"1985 –", durum:"faal", aile:0, donem:4,
     sembol:"Güvercin", not:"Ecevit çizgisi, CHP'den ayrı damar"},
    {id:"anap", kisa:"ANAP", ad:"Anavatan Partisi", yil:"1983 – 2009", durum:"katildi", aile:1, donem:4,
     sembol:"Bal peteği", not:"\"Dört eğilimi birleştirme\" iddiası; Özal"},
    {id:"dyp", kisa:"DYP", ad:"Doğru Yol Partisi", yil:"1983 – 2007", durum:"katildi", aile:1, donem:4,
     sembol:"Kır at", not:"AP'nin doğrudan devamı"},
    {id:"rp", kisa:"RP", ad:"Refah Partisi", yil:"1983 – 1998", durum:"kapatildi", aile:2, donem:4,
     not:"1996–97 arası iktidar ortağı"},
    {id:"mcp", kisa:"MÇP", ad:"Milliyetçi Çalışma Partisi", yil:"1983 – 1993", durum:"katildi", aile:3, donem:4,
     not:"MHP'nin kapatılma sonrası devamı"},
    {id:"mdp", kisa:"MDP", ad:"Milliyetçi Demokrasi Partisi", yil:"1983 – 1986", durum:"kapandi", aile:1, donem:4,
     not:"12 Eylül sonrası kurulan ilk parti; 1983'te üçüncü"},
    {id:"hep", kisa:"HEP", ad:"Halkın Emek Partisi", yil:"1990 – 1993", durum:"kapatildi", aile:5, donem:4,
     not:"SHP'den ayrılan milletvekilleriyle kuruldu"},
    {id:"tbkp", kisa:"TBKP", ad:"Türkiye Birleşik Komünist Partisi", yil:"1990 – 1991", durum:"kapatildi", aile:4, donem:4,
     not:"TKP ile TİP'in birleşmesi"},

    // --- dönem 5 ---
    {id:"chp92", kisa:"CHP", ad:"Cumhuriyet Halk Partisi", yil:"1992 –", durum:"faal", aile:0, donem:5,
     sembol:"Altı Ok", not:"Kapalı kaldığı 11 yılın ardından aynı adla yeniden açıldı"},
    {id:"dp92", kisa:"DP", ad:"Demokrat Parti", yil:"1992 – 2005", durum:"katildi", aile:1, donem:5,
     not:"CHP ile aynı yasayla yeniden açıldı; 2005'te isim hakkıyla ANAP'a katıldı"},
    {id:"dtp97", kisa:"DTP", ad:"Demokrat Türkiye Partisi", yil:"1997 – 2005", durum:"katildi", aile:1, donem:5,
     sembol:"Şemsiye", not:"DYP'den kopan \"Yeni Oluşumcular\"; 2005'te HÜRPARTİ oldu"},
    {id:"ldp", kisa:"LDP", ad:"Liberal Demokrat Parti", yil:"1994 –", durum:"faal", aile:6, donem:5,
     sembol:"Yunus", not:"Tibuk, DP genel başkanlığını kaybedince ayrılıp kurdu"},
    {id:"ydh", kisa:"YDH", ad:"Yeni Demokrasi Hareketi", yil:"1994 – 1997", durum:"katildi", aile:6, donem:5,
     not:"Boyner liderliğinde, ağırlıkla sol kökenli aydın ve iş insanı kadrosu"},
    {id:"mhp93", kisa:"MHP", ad:"Milliyetçi Hareket Partisi", yil:"1993 –", durum:"faal", aile:3, donem:5,
     sembol:"Üç hilal", not:"MÇP'nin adını yeniden alması"},
    {id:"bbp", kisa:"BBP", ad:"Büyük Birlik Partisi", yil:"1993 –", durum:"faal", aile:3, donem:5,
     not:"MHP'den ayrılan Yazıcıoğlu kanadı"},
    {id:"fp", kisa:"FP", ad:"Fazilet Partisi", yil:"1997 – 2001", durum:"kapatildi", aile:2, donem:5,
     not:"Refah kapatılınca kuruldu"},
    {id:"dep", kisa:"DEP", ad:"Demokrasi Partisi", yil:"1993 – 1994", durum:"kapatildi", aile:5, donem:5},
    {id:"hadep", kisa:"HADEP", ad:"Halkın Demokrasi Partisi", yil:"1994 – 2003", durum:"kapatildi", aile:5, donem:5},
    {id:"dehap", kisa:"DEHAP", ad:"Demokratik Halk Partisi", yil:"1997 – 2005", durum:"katildi", aile:5, donem:5},
    {id:"odp", kisa:"ÖDP", ad:"Özgürlük ve Dayanışma Partisi", yil:"1996 – 2019", durum:"katildi", aile:4, donem:5,
     not:"Sosyalist grupların birleşmesi; 2019'da adı Sol Parti oldu"},
    {id:"emep", kisa:"EMEP", ad:"Emek Partisi", yil:"1996 –", durum:"faal", aile:4, donem:5},
    {id:"ip92", kisa:"İP", ad:"İşçi Partisi", yil:"1992 – 2015", durum:"katildi", aile:4, donem:5,
     not:"Perinçek çizgisi"},

    // --- dönem 6 ---
    {id:"akp", kisa:"AK Parti", ad:"Adalet ve Kalkınma Partisi", yil:"2001 –", durum:"faal", aile:2, donem:6,
     sembol:"Ampul", not:"Fazilet'in \"yenilikçi\" kanadı"},
    {id:"sp", kisa:"SP", ad:"Saadet Partisi", yil:"2001 –", durum:"faal", aile:2, donem:6,
     not:"Fazilet'in \"gelenekçi\" kanadı"},
    {id:"has", kisa:"HAS Parti", ad:"Halkın Sesi Partisi", yil:"2010 – 2012", durum:"katildi", aile:2, donem:6,
     not:"Saadet'ten ayrılan Kurtulmuş; AK Parti ile bütünleşti"},
    {id:"ytp02", kisa:"YTP", ad:"Yeni Türkiye Partisi", yil:"2002 – 2004", durum:"katildi", aile:0, donem:6,
     not:"DSP'den ayrılan 63 vekil, İsmail Cem liderliğinde"},
    {id:"anadolu", kisa:"Anadolu P.", ad:"Anadolu Partisi", yil:"2014 – 2015", durum:"kapandi", aile:0, donem:6,
     not:"CHP'den ayrılan Emine Ülker Tarhan"},
    {id:"dp07", kisa:"DP", ad:"Demokrat Parti", yil:"2007 –", durum:"faal", aile:1, donem:6,
     not:"DYP'nin ad değişikliği; 2009'da ANAP katıldı"},
    {id:"dtp", kisa:"DTP", ad:"Demokratik Toplum Partisi", yil:"2005 – 2009", durum:"kapatildi", aile:5, donem:6},
    {id:"bdp", kisa:"BDP", ad:"Barış ve Demokrasi Partisi", yil:"2008 – 2014", durum:"katildi", aile:5, donem:6,
     not:"2014'te DBP adını aldı, vekiller HDP'ye geçti"},
    {id:"hdp", kisa:"HDP", ad:"Halkların Demokratik Partisi", yil:"2012 –", durum:"faal", aile:5, donem:6},
    {id:"hudapar", kisa:"HÜDA PAR", ad:"Hür Dava Partisi", yil:"2012 –", durum:"faal", aile:2, donem:6,
     not:"2023'te adayları AK Parti listelerinden meclise girdi"},
    {id:"yesilsol", kisa:"YSP", ad:"Yeşil Sol Parti", yil:"2012 – 2023", durum:"katildi", aile:5, donem:6,
     not:"2023 seçimlerinde HDP'nin listesi oldu"},
    {id:"vatan", kisa:"Vatan P.", ad:"Vatan Partisi", yil:"2015 –", durum:"faal", aile:4, donem:6,
     not:"İşçi Partisi'nin ad değişikliği"},

    // --- dönem 7 ---
    {id:"memleket", kisa:"Memleket P.", ad:"Memleket Partisi", yil:"2021 – 2025", durum:"katildi", aile:0, donem:7,
     not:"İnce 2025'te CHP'ye döndü; parti kurultay kararıyla kapandı"},
    {id:"tdp", kisa:"TDP", ad:"Türkiye Değişim Partisi", yil:"2020 – 2023", durum:"katildi", aile:0, donem:7,
     not:"Mustafa Sarıgül; 2023'te CHP ile birleşti"},
    {id:"yeniparti", kisa:"Yeni Parti", ad:"Yeni Parti", yil:"2026 –", durum:"faal", aile:0, donem:7,
     not:"Özel ve 91 vekilin ayrılışı; TBMM'de ana muhalefet"},
    {id:"yrp", kisa:"YRP", ad:"Yeniden Refah Partisi", yil:"2018 –", durum:"faal", aile:2, donem:7,
     not:"Saadet'ten ayrılan Erbakan çizgisi"},
    {id:"gelecek", kisa:"Gelecek P.", ad:"Gelecek Partisi", yil:"2019 – 2026", durum:"kapandi", aile:2, donem:7,
     not:"AK Parti'den ayrılan Davutoğlu; Temmuz 2026'da feshedildi"},
    {id:"deva", kisa:"DEVA", ad:"Demokrasi ve Atılım Partisi", yil:"2020 –", durum:"faal", aile:2, donem:7,
     not:"AK Parti'den ayrılan Babacan"},
    {id:"yeniyol", kisa:"Yeni Yol", ad:"Yeni Yol Partisi", yil:"2025 –", durum:"faal", aile:2, donem:7,
     not:"Saadet + Gelecek + DEVA'nın ortak Meclis grubu; partiler ayrı kaldı"},
    {id:"iyi", kisa:"İYİ Parti", ad:"İyi Parti", yil:"2017 –", durum:"faal", aile:3, donem:7,
     sembol:"16 ışınlı güneş", not:"MHP'den ayrılan Akşener kanadı"},
    {id:"zafer", kisa:"Zafer P.", ad:"Zafer Partisi", yil:"2021 –", durum:"faal", aile:3, donem:7,
     not:"İYİ Parti'den ayrılan Özdağ"},
    {id:"anahtar", kisa:"A Parti", ad:"Anahtar Parti", yil:"2024 –", durum:"faal", aile:3, donem:7,
     sembol:"Anahtar", not:"İYİ Parti'den ayrılan Ağıralioğlu; amblemi MSP'yi andırıyor"},
    {id:"dem", kisa:"DEM Parti", ad:"Halkların Eşitlik ve Demokrasi Partisi", yil:"2023 –", durum:"faal", aile:5, donem:7,
     not:"Yeşil Sol Parti'nin ad değişikliği"},
    {id:"tip17", kisa:"TİP", ad:"Türkiye İşçi Partisi", yil:"2017 –", durum:"faal", aile:4, donem:7,
     not:"Tarihsel TİP adının yeniden kullanımı"},

    // --- sonradan eklenenler: seçim verisinde geçen, ağaçta olmayan partiler ---
    {id:"tukp", kisa:"TUKP", ad:"Türkiye Ulusal Kadınlar Partisi", yil:"1972 – 1981", durum:"kapatildi", aile:6, donem:3,
     not:"Türkiye'nin ilk yasal kadın partisi"},
    {id:"tsip74", kisa:"TSİP", ad:"Türkiye Sosyalist İşçi Partisi", yil:"1974 – 1981", durum:"kapatildi", aile:4, donem:3,
     not:"12 Mart sonrası kurulan ilk sosyalist parti"},
    {id:"sdp75", kisa:"SDP", ad:"Sosyalist Devrim Partisi", yil:"1975 – 1981", durum:"kapatildi", aile:4, donem:3,
     not:"Aybar'ın partisi; kuruluştaki adı Sosyalist Parti"},
    {id:"idp", kisa:"IDP", ad:"Islahatçı Demokrasi Partisi", yil:"1984 – 1992", durum:"katildi", aile:3, donem:4,
     not:"1992'de adı Millet Partisi oldu"},
    {id:"mp92", kisa:"MP", ad:"Millet Partisi", yil:"1992 –", durum:"faal", aile:3, donem:5,
     not:"IDP'nin ad değişikliği; Aykut Edibali"},
    {id:"sbp91", kisa:"SBP", ad:"Sosyalist Birlik Partisi", yil:"1991 – 1995", durum:"kapatildi", aile:4, donem:5,
     not:"Sadun Aren; Anayasa Mahkemesince kapatıldı"},
    {id:"ydp", kisa:"YDP", ad:"Yeniden Doğuş Partisi", yil:"1992 – 2002", durum:"katildi", aile:1, donem:5,
     not:"ANAP'tan ayrılan Güzel; 2002'de adı Genç Parti oldu"},
    {id:"sip93", kisa:"SİP", ad:"Sosyalist İktidar Partisi", yil:"1993 – 2001", durum:"katildi", aile:4, donem:5,
     not:"2001'de adı Türkiye Komünist Partisi oldu"},
    {id:"baris96", kisa:"BP", ad:"Barış Partisi", yil:"1996 – 1999", durum:"kapandi", aile:0, donem:5,
     not:"Ali Haydar Veziroğlu; 1999'da kendini feshetti"},
    {id:"dbp96", kisa:"DBP", ad:"Demokrasi ve Barış Partisi", yil:"1996 – 2002", durum:"katildi", aile:5, donem:5,
     not:"Refik Karakoç; 2002'de HAK-PAR ile birleşti"},
    {id:"depar", kisa:"DEPAR", ad:"Değişen Türkiye Partisi", yil:"1998 – 2002", durum:"kapandi", aile:0, donem:5,
     not:"DSP'den ayrılan Gökhan Çapoğlu"},
    {id:"genc", kisa:"Genç Parti", ad:"Genç Parti", yil:"2002 –", durum:"faal", aile:1, donem:6,
     not:"Cem Uzan; YDP'nin ad değişikliği"},
    {id:"shp02", kisa:"SHP", ad:"Sosyaldemokrat Halk Partisi", yil:"2002 – 2010", durum:"katildi", aile:0, donem:6,
     not:"Murat Karayalçın; 2010'da EDP ile birleşti"},
    {id:"btp", kisa:"BTP", ad:"Bağımsız Türkiye Partisi", yil:"2001 –", durum:"faal", aile:3, donem:6,
     not:"Haydar Baş; \"Millî Ekonomi Modeli\""},
    {id:"tkp01", kisa:"TKP", ad:"Türkiye Komünist Partisi", yil:"2001 –", durum:"faal", aile:4, donem:6,
     not:"SİP'in ad değişikliği; 1920 TKP'sinden ayrı parti"},
    {id:"hakpar", kisa:"HAK-PAR", ad:"Hak ve Özgürlükler Partisi", yil:"2002 –", durum:"faal", aile:5, donem:6,
     not:"Kürt kimliği ve federal yapı savunusu"},
    {id:"edp", kisa:"EDP", ad:"Eşitlik ve Demokrasi Partisi", yil:"2010 – 2012", durum:"katildi", aile:4, donem:6,
     not:"SHP ve ÖDP'den ayrılanlar; 2012'de Yeşiller ile birleşti"},
    {id:"solparti", kisa:"SOL Parti", ad:"Sol Parti", yil:"2019 –", durum:"faal", aile:4, donem:7,
     not:"ÖDP'nin ad değişikliği"},
    {id:"vp54", kisa:"VP", ad:"Vatan Partisi", yil:"1954 – 1957", durum:"kapatildi", aile:4, donem:1,
     not:"Hikmet Kıvılcımlı; mahkeme kararıyla kapatıldı"},
    {id:"turkparti", kisa:"TURK PARTİ", ad:"Toplumsal Uzlaşma Reform ve Kalkınma Partisi", yil:"2010 – 2015", durum:"kapandi", aile:6, donem:6,
     not:"Ahmet Eyüp Özgüç; 2015'te kongre kararıyla feshedildi"},
    {id:"hkp", kisa:"HKP", ad:"Halkın Kurtuluş Partisi", yil:"2005 –", durum:"faal", aile:4, donem:6,
     not:"Nurullah Efe; komünist parti"}
  ];

  const E = [
    ["chp23","tcf","bolunme"], ["chp23","scf","bolunme"],
    ["chp23","hp83","bolunme"], ["chp23","sodep","bolunme"],
    ["hp83","shp","katilma"], ["sodep","shp","katilma"],
    ["chp23","chp92","devam"],
    ["chp23","gp","bolunme"], ["chp23","cp72","bolunme"],
    ["dp46","hurriyet","bolunme"], ["hurriyet","chp23","katilma"],
    ["gp","cgp","katilma"], ["cp72","cgp","katilma"],
    ["shp","chp92","katilma"], ["chp23","dsp","bolunme"],
    ["chp92","memleket","bolunme"], ["memleket","chp92","katilma"],
    ["chp92","yeniparti","bolunme"], ["shp","hep","bolunme"],
    ["dsp","ytp02","bolunme"], ["ytp02","chp92","katilma"],
    ["chp92","anadolu","bolunme"],
    ["dsp","tdp","bolunme"], ["tdp","chp92","katilma"],

    ["dp46","ap","devam"], ["dp46","ytp","devam"], ["dp46","dp92","devam"],
    ["dp92","ldp","bolunme"], ["dp92","anap","katilma"],
    ["shp","ydh","bolunme"], ["tip61","ydh","bolunme"],
    ["ap","demp70","bolunme"], ["demp70","ap","katilma"],
    ["ap","dyp","devam"], ["ap","anap","bolunme"],
    ["dyp","dp07","devam"], ["anap","dp07","katilma"],
    ["dyp","dtp97","bolunme"],

    ["mnp","msp","devam"], ["msp","rp","devam"], ["rp","fp","devam"],
    ["fp","sp","devam"], ["fp","akp","bolunme"],
    ["sp","yrp","bolunme"], ["sp","has","bolunme"], ["has","akp","katilma"],
    ["akp","gelecek","bolunme"], ["akp","deva","bolunme"],
    ["sp","yeniyol","katilma"], ["gelecek","yeniyol","katilma"], ["deva","yeniyol","katilma"],

    ["mp48","cmp","devam"], ["cmp","ckmp","devam"], ["ckmp","mhp69","devam"], ["ckmp","mp62","bolunme"],
    ["mhp69","mcp","devam"], ["mcp","mhp93","devam"],
    ["mhp93","bbp","bolunme"], ["mhp93","iyi","bolunme"], ["iyi","zafer","bolunme"],
    ["iyi","anahtar","bolunme"],

    ["hep","dep","devam"], ["dep","hadep","devam"], ["hadep","dehap","devam"],
    ["dehap","dtp","devam"], ["dtp","bdp","devam"], ["bdp","hdp","katilma"],
    ["yesilsol","dem","devam"], ["hdp","dem","bolunme"],

    ["tkp20","thif","devam"], ["tkp20","tbkp","katilma"], ["tip61","tip75","devam"], ["tip75","tbkp","katilma"],
    ["tip75","odp","bolunme"], ["tip75","emep","bolunme"],
    ["tip61","tip17","bolunme"], ["ip92","vatan","devam"],
    ["idp","mp92","devam"], ["anap","ydp","bolunme"], ["ydp","genc","devam"], ["sip93","tkp01","devam"], ["dbp96","hakpar","katilma"], ["dsp","depar","bolunme"], ["shp02","edp","katilma"], ["odp","edp","bolunme"], ["edp","yesilsol","katilma"], ["odp","solparti","devam"], ["tkp52","ckmp","katilma"]
  ];

  const ROZET = {
    kapatildi:["kapatıldı","r-kapatildi"],
    faal:["faal","r-faal"],
    katildi:["devredildi","r-katildi"],
    kapandi:["feshedildi","r-katildi"]
  };
  return {AILE, BILGI, DONEMLER, N, E, ROZET};
})();
